### ISSUE TITLE
Not able to create multiple OCI datasources

### ISSUE THREAD

**Issue by varmaimmalraju** [oracle/oci-grafana-metrics#100]
We have resources under multiple tenants each by its own OCI profile name in oci config. The plugin defaults to the DEFAULT profile. Is there a way we can pull metrics from other profiles as well. If there is no option at the moment, adding profiles as an option would help.

**Comment by chillaxd** [comment]
HI @simmalra Please have a look into https://github.com/oracle/oci-grafana-metrics/pull/106. I have changed it so that it can work multiple profile. It is still on developing phase. But you can have a look and try. 
If you need any help or clarification feel free to let me know.

**Comment by vmuthadi-winfo** [comment]
@chillaxd  I deploying latest #106 to my grafana system and updated datasource settings. Do we have new variable added to link tenancies to chose from list (or) How to select the required tenancy from dashboard

**Comment by chillaxd** [comment]
Hi @vmuthadi-winfo sorry for late response. For tenancies, currently plugin will require tenancies file path of which you can get in datasource configuration.
I have attached the sample screenshot of the datasource configuration. Format of the tenancies file will be
<tenancy_name>,<tenancy_ocid>

and please remember create the oci profile with <tenancy_name>

Please let me know if you need any further help.

<img width="903" alt="Screenshot 2021-07-28 at 12 09 08 PM" src="https://user-images.githubusercontent.com/8392039/141783973-a299d462-b3cd-4392-a1e1-148da81a2ae8.png">
.

**Comment by vmuthadi-winfo** [comment]
@chillaxd Thanks for the update. I am able to configure the data source successfully, but I would like parameterize the tenancy. I can choose the tenancy from the list under panel but I am looking at templatizing where in I get error. Below are screenshots

![image](https://user-images.githubusercontent.com/64590060/141788226-6e057aaa-288e-432a-b483-2c88a6019261.png)

Could not identify the correct variable name and also unable it use variables like regions(),etc.,
![image](https://user-images.githubusercontent.com/64590060/141788290-ac41dc19-373a-4c86-84c9-422384b1f75b.png)

**Comment by chillaxd** [comment]
HI @vmuthadi-winfo unfortunately I have not implemented the variable features in the new plugin yet. So that's why it is giving error.

**Comment by huskerdhf** [comment]
@YogiTiwari Currently the plugin still only supports a single tenancy per plugin instance. However there is ongoing work to update the plugin to support accessing multiple tenancies from a single plugin instance. Although in your case it looks like you are creating distinct plugin instances.

So for your use case, you have cross tenancy permissions setup to allow compartment list and metrics access to tenancy B (where Grafana is **NOT** installed) from tenancy A (where Grafana **IS** installed), correct? The reason I ask is that supporting multiple tenancies from the plugin is slightly different depending on whether one is using a local OCI configuration file or instance principals and so I just wanted to confirm your particular use case.

Finally, in the information you shared you didn't show the compartments being listed for tenancy B **from** tenancy A. Did you try that via the OCI CLI from the instance in tenancy A? Also I would suggest that you confirm the policy to allow compartment read access within tenancy B **from** tenancy A has been applied in tenancy A. Where the single tenancy version of the policy would be:
`allow group grafana to read compartments in tenancy`

**Comment by YogiTiwari** [comment]
Hi,
We were missing a pemission in the policy. 

Earlier we missed  read tenancies in tenancy
<img width="743" alt="image" src="https://user-images.githubusercontent.com/81763997/202369899-a23ea095-95a0-4b38-a2a8-3b79504c5b94.png">

**Comment by huskerdhf** [comment]
Okay, glad you resolved it.
