### ISSUE TITLE
[CRITICAL] No support to Grafana 8

### ISSUE THREAD

**Issue by MaikiGirardi** [oracle/oci-grafana-metrics#109]
HI, i'm reopening the issue because the other one was closed and there is no release solving the problem. 

The original issue #91

**Comment by chillaxd** [comment]
@MaikiGirardi my PR is still under review. And honestly I don't have any idea how long it will take to merge it. In the mean time with every changes I am updating the build under release directory. You can directly download it and replace  plugins/oci-metrics-datasource/dist with the new dist from zip.

**Comment by MaikiGirardi** [comment]
@chillaxd can you please share your Datasource configs right now and if i have to change CLI installation? After apply this new version i'm facing 404 when testing.

![image](https://user-images.githubusercontent.com/20565056/141293902-b234c7f2-efa2-4572-ac13-aad4398afbd5.png)

**Comment by chillaxd** [comment]
Hi @MaikiGirardi  sorry for late response. I have added the screenshot of the datasource configuration here.

For multi tenancies, currently plugin will require tenancies file path, which you can get in datasource configuration.
Format of the tenancies file will be
<tenancy_name>,<tenancy_ocid>

and please remember create the oci profile with <tenancy_name>

Please let me know if you need any further help
<img width="903" alt="Screenshot 2021-07-28 at 12 09 08 PM" src="https://user-images.githubusercontent.com/8392039/141784416-79eb0447-792c-460f-8ed8-0fbc7148779f.png">
.

**Comment by MaikiGirardi** [comment]
Sorry for the delay, i found my problem, my Grafana and OCI-CLI version was too old for those changes. After i upgraded for the last version on both it start working properly. 

Right now, on my tests, i found some critical issues  that makes me wait. I don't know, do you want me to report those issues? If yes, where i can open those issues?

Thanks @chillaxd

**Comment by chillaxd** [comment]
@MaikiGirardi Sorry for late response. Please put the issues here as I am currently in enhancement mode for this plugin so I can so if I have already covered those or not.

**Comment by MaikiGirardi** [comment]
@chillaxd, i put the issues i've found on the PR #106 . If it helps, please let me know. When did you will release this? There is any planned date?

**Comment by mayurOciSA** [comment]
@MaikiGirardi the latest 3.0.0 on Grafana marketplace(same as latest on a main branch here) supports Grafana 8, it has few additional minor updates too. Please use that.

**Comment by MaikiGirardi** [comment]
I've tested the version 3.0.0 and the plugin starts working again on Grafana 8! Thx

**Comment by mayurOciSA** [comment]
@MaikiGirardi we regret to be late to update the docs...we will soon post it to Github and to the Grafana Marketplace too...BTW the new version has a few additional improvements .... fully qualified cmpt names and you will also see dimensions for each metric stream in UI

**Comment by MaikiGirardi** [comment]
@mayurOciSA The time frame to release this bug fix was really bad. Please, in the future don't merge new features with bug fix as i could see that's the problem. I hope this plugin keep improving as i can see on PR #106 that are covering a lot of needs like support for alerts and multi tenant. And, maybe one day, remove the need OCI-CLI like other vendors. 

Anyway, thanks right now i could update my grafana server properly.
