### ISSUE TITLE
The OCI Logs plugin does not work while the Metrics one does?

### ISSUE THREAD

**Issue by jingrma** [oracle/oci-grafana-metrics#114]
Anyone having the same issue? 
I have configured Grafana 8 in a local docker env. 
The OCI Metrics (3.0.0) working fine, but for the same configuration the Logs plugin (1.1.0) does NOT work. 

![image](https://user-images.githubusercontent.com/99995354/154772754-53b0961a-2184-4f61-a8f3-ef5cfe08f925.png)

I have the IAM policy setup as
![image](https://user-images.githubusercontent.com/99995354/154772791-81aa0ec9-3f19-4269-8479-7314bc22151a.png)

**Comment by huskerdhf** [comment]
Hi @jingrma,

This issue is being closed since the issue is related to the oci-grafana-logs plugin rather than the oci-grafana-metrics plugin.

FYI from the 2.0.0 version forward the oci-grafana-logs plugin works with Grafana 8.
