### ISSUE TITLE
Issue with variables and templates in using.md

### ISSUE THREAD

**Issue by akhodaba** [oracle/oci-grafana-metrics#12]
Hello, Hi @mickeyboxell  , Hi @rosalexander , 

I am following the documentation [0] to create a dashboard, but I am hitting some errors in the templating.
I have defined the 4 variables (region, compartment, namespace and metric) [1].
They do show up at the top of my dashboard. But I have these issues:

1- The "metric" does not appear to be working. The preview values do not show at the definition time, and the corresponding pop up remains empty [2]
2- Also I get the error message in the top left corner of the graph regularly [3].

However the metric field does work in the query directly [4] and [5]

Do you know if this is an error on my side or in the documentation?

Many thanks for your help,
Arash Khodabandeh

[0] https://github.com/oracle/oci-grafana-plugin/blob/master/docs/using.md
[1] 01-variables-definition.jpg
![01-variables-definition](https://user-images.githubusercontent.com/13148996/58333988-e9f91c80-7e3e-11e9-8165-fc060da77764.JPG)
[2] 02-empty-metric-popup.jpg
![02-empty-metric-popup](https://user-images.githubusercontent.com/13148996/58333999-ef566700-7e3e-11e9-972b-3752c3420df5.JPG)
[3] 03-error-message.jpg
![03-error-message](https://user-images.githubusercontent.com/13148996/58334011-f2515780-7e3e-11e9-9739-75f752b93e3b.JPG)
[4] 04-metric-popup-in-query.jpg
![04-metric-popup-in-query](https://user-images.githubusercontent.com/13148996/58334013-f54c4800-7e3e-11e9-9d21-c7cb130ac00d.JPG)
[5] 05-working-graph.jpg
![05-working-graph](https://user-images.githubusercontent.com/13148996/58334024-f7aea200-7e3e-11e9-9a73-cd31914d9ad0.JPG)

**Comment by mickeyboxell** [comment]
Hi @akhodaba sorry for the delay - I just returned from vacation. I was unable to reproduce the issue on my end. I just went through the process of recreating all four variables on a Kubernetes  environment in Oracle Cloud running Grafana 6.x with the 1.0.2 release of the plugin. 

![variables](https://user-images.githubusercontent.com/11068865/58731278-2d094180-83a3-11e9-8250-0af5929c147f.png)

**Comment by akhodaba** [comment]
Hello @mickeyboxell , thank you for taking the time to review and for your comment. I am using the same version of the plugin. I have restarted the installation twice to check and each time I could reproduce it. I copy below the steps I have followed on a clean empty host located at CERN. I indicate each time which documentation I used to do the specific operation.

Did you do the test on a host in OCI ?

If you have a moment to review my procedure in case you identify anything it would certainly help.

And if you have your own procedure I could try it on my side as well.

Regards,
Arash

```
# The VM is called grafanaoci01
-bash-4.2$ ssh grafanaoci01

# installation following
# https://medium.com/@nalixandru/monitoring-oracle-cloud-infrastructure-with-grafana-f0e2945d2eec
-bash-4.2$ sudo yum install wget
-bash-4.2$ wget https://dl.grafana.com/oss/release/grafana-6.1.6-1.x86_64.rpm
-bash-4.2$ sudo yum localinstall grafana-6.1.6-1.x86_64.rpm
-bash-4.2$ sudo vi /etc/grafana/grafana.ini
update the fields
protocol = http
http_port = 3000
domain = grafanaoci01.cern.ch
root_url = %(protocol)s://%(domain)s:%(http_port)s/

# open port 3000 in the firewall
-bash-4.2$ sudo firewall-cmd --zone=public --add-port=3000/tcp --permanent
-bash-4.2$ sudo firewall-cmd --reload

# Install plugin following
# https://blogs.oracle.com/cloudnative/data-source-grafana
-bash-4.2$ sudo grafana-cli plugins install oci-datasource
-bash-4.2$ sudo service grafana-server restart

# start OCI user setup following
# https://grafana.com/plugins/oci-datasource
oci portal: create locale grafana user

# generate the key following
# https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm
-bash-4.2$ sudo mkdir /usr/share/grafana/.oci
-bash-4.2$ sudo openssl genrsa -out /usr/share/grafana/.oci/oci_api_key.pem 2048
-bash-4.2$ sudo chmod go-rwx /usr/share/grafana/.oci/oci_api_key.pem
-bash-4.2$ sudo openssl rsa -pubout -in /usr/share/grafana/.oci/oci_api_key.pem -out /usr/share/grafana/.oci/oci_api_key_public.pem
# and the finger print
-bash-4.2$ sudo openssl rsa -pubout -outform DER -in /usr/share/grafana/.oci/oci_api_key.pem | openssl md5 -c

-bash-4.2$ sudo vi /usr/share/grafana/.oci/config
[DEFAULT]
user=ocid1.user.oc1..aaaaaaaajixtw7w7knu27rhtneq6acpi7e33hzaf6hlcmb7sfeh66el6xzea
fingerprint=c7:bf:4c:1e:77:67:98:af:12:67:7a:2d:a7:f9:3a:93
key_file=/usr/share/grafana/.oci/oci_api_key.pem
tenancy=ocid1.tenancy.oc1..aaaaaaaakr2urkzeh437nc7myq52f5k6idd44cwkgkw6o76jowxrffpnvxkq
region=eu-frankfurt-1

# continue user setup following
# https://blogs.oracle.com/cloudnative/data-source-grafana
oci portal: upload in grafana the public key generated above
oci portal: create Grafana group
oci portal: add grafana user to Grafana group
oci portal: add GrafanaPolicy with
allow group Grafana to read metrics in tenancy
allow group Grafana to read compartments in tenancy 

```

**Comment by mickeyboxell** [comment]
Hi @akhodaba I was using a host in OCI. I will run through the steps on a Oracle Linux VM outside of OCI. Which OS are you running? Here is the link to the steps I followed: https://github.com/oracle/oci-grafana-plugin/blob/master/Readme.md#installation-documentation

**Comment by akhodaba** [comment]
Hi @mickeyboxell . I am running this on CC7.
```
-bash-4.2$ uname -a
Linux grafanaoci01.cern.ch 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
The instructions you pointed me too are indeed what I also looked at.

**Comment by mickeyboxell** [comment]
Hi @akhodaba I was able to walk through the Grafana configuration from scratch on a local Oracle Linux VM with authentication via the OCI CLI. I am running into a similar issue in which the metrics template variable does not properly load the list of values to choose from. I will ask one of our development teams take a look. 

<img width="830" alt="variable-error" src="https://user-images.githubusercontent.com/11068865/58989431-bef4be00-8798-11e9-97af-ad311ae218f6.png">

**Comment by akhodaba** [comment]
Hi @mickeyboxell , I am very grateful for your test. Please do not hesitate to let me know if there is anything you want me to check or test on my side.

**Comment by akhodaba** [comment]
Hi @mickeyboxell , I just wanted to check with you if there are more investigations and if by chance you would have a BUG tracking number that I could follow in support.oracle.com portal? Cheers.

**Comment by mboxell** [comment]
Hi @akhodaba since this is being worked on outside of my team, my visibility is limited. It looks like the ticket number is 3-20163161741, but I don't see a bug number. Is it possible for you to use the workaround of having the Grafana instance deployed on a server in OCI that authenticates with Instance Principals?

**Comment by akhodaba** [comment]
I see @mickeyboxell . The SR you mention is mine. It was force closed by support despite I insisted that it should be kept open until a fix is provided. They also refused to escalate it or to assign it to the team for a better interaction with me. To be complete, I even had to fight to open that SR as originally support claimed that as this is Grafana related I should go to the Grafana forums! I get the message that there is no desire to fix this. I was even asked to justify my business case! Very frustrating.

The workaround is not the way we want to go as we have our infrastructure. It could be a matter of validating the fact, but you have kindly done it.

If you have a way to put a bit of pressure and have at least a bug opened I would be happy to follow its progress via the support portal.

**Comment by mboxell** [comment]
Hi @akhodaba I'm sorry to hear that. I'll do what I can to reengage that team. I wish there was more I can do to help.

**Comment by VadimKomar** [comment]
Hi @akhodaba please check the latest version https://github.com/oracle/oci-grafana-plugin/releases/tag/V1.0.4 and notify me if the problem is reproducible.
p.s. Only manual plugin installation is available.

**Comment by mikwagner** [comment]
I am also facing the same issue with v1.0.4.  Datasource works fine when designing a dashboard from scratch.  But as soon as I get to 'namespaces' when adding variables (per the kubernetes readme), it starts crashing all over the place.

**Comment by mamorett** [comment]
all Templates vars are working as expected in recent version of the plugin
