### ISSUE TITLE
Can I configure this datasource in Grafana Cloud?

### ISSUE THREAD

**Issue by paolajuarezgomez** [oracle/oci-grafana-metrics#142]
If you are running Grafana anywhere else, make sure you have ~/.oci configured properly. You can do this by installing the Oracle Cloud CLI and running the setup.

How can I configure .oci in grafana cloud?.

Regards

**Comment by felipehma** [comment]
We are experiencing the same blocking issue trying to make use Grafana Cloud, maybe here the best choice would be to use [Oracle Monitoring REST-API endpoints](https://docs.oracle.com/en-us/iaas/api/#/en/monitoring/20180401/), as an example, in place of Oracle Cloud CLI, isn't? 

Not sure if there is any plan to make use if it.

**Comment by kz4d1x** [comment]
Hi @paolajuarezgomez, please check the latest release of the metrics plugin, it supports the Grafana Cloud integration. https://github.com/oracle/oci-grafana-metrics/releases/tag/v4.0.0
