### ISSUE TITLE
OCI Metrics plugin for Grafana Cloud

### ISSUE THREAD

**Issue by YogiTiwari** [oracle/oci-grafana-metrics#155]
Hi,
Is there a OCI Grafana plugin available in Cloud version of Grafana?

Regards
Yogesh

**Comment by kz4d1x** [comment]
Hi @YogiTiwari , please check the latest release of the metrics plugin, it supports the Grafana Cloud integration. https://github.com/oracle/oci-grafana-metrics/releases/tag/v4.0.0
