### ISSUE TITLE
support for $resolution variable - similarly to $metric or $region

### ISSUE THREAD

**Issue by damikem** [oracle/oci-grafana-metrics#19]
Support in such a variable will allow to get responses from OCI for big queries that would otherwise fail (or just will be slow), e.g get metrics for 100 servers for the last 7 days.
By controlling the resolution of all the panels in the dashboard I can make changes in one click, instead of going one panel after another.

**Comment by damikem** [comment]
The maintainer of this repository should at least share his thoughts about the feature

**Comment by mamorett** [comment]
Introduced in v5.2.0.
