### ISSUE TITLE
Is it possible to do some math between metrics?

### ISSUE THREAD

**Issue by JavierCCC** [oracle/oci-grafana-metrics#209]
I need to monitor de amount of available/healthy backend servers behind a LBAAS. There are two metrcis, BackendServers and UnHealtyBackendServers. I need to show:

BackendServers - UnHealtyBackendServers

The plugin doesnt allow expressions between queries: is there any way to achieve this?

**Comment by mamorett** [comment]
Hi. Can you share the queries you are using ? Thanks.

**Comment by mamorett** [comment]
Hi Javier. Unfortunately I do not think you will be able to do math between these two queries. You can display both graph on the same panel but not do math.

**Comment by JavierCCC** [comment]
So, i was able to achieve the metric i was looking for using the text edit mode with this query:

BackendServers[1m].mean() - UnHealthyBackendServers[1m].mean()
