### ISSUE TITLE
Grafana 9 and metrics plugin

### ISSUE THREAD

**Issue by JavierCCC** [oracle/oci-grafana-metrics#210]
Hi,
We are currently using Grafana 9.5.2, and OCI grafana metrics plugin versión 3.0.6. We have already tried an upgrade to plugin versión 4.0.1 with no success. I think is related to: 

"Latest plugin version 4.X.X(available on [Grafana Marketplace](https://grafana.com/grafana/plugins/oci-metrics-datasource/)) is compatible with Grafana 8**."

Is 4.0.1 not compatible with grafana 9.xxx? If so, will the updated plugin be available in a near future for newer Grafana versions like 9.xxx?

**Comment by mamorett** [comment]
Please upgrade to version 5.0.0 of the plugin, this newer version is compatible with Grafana 9.x
