### ISSUE TITLE
Cannot read properties of undefined (reading 'details')

### ISSUE THREAD

**Issue by Nefnief-tech** [oracle/oci-grafana-metrics#212]
I configured the plugin correctly but: Cannot read properties of undefined (reading 'details')

**Comment by mamorett** [comment]
Hi. I would need more information about this issue. Are you trying to configure the datasource ? In this case, using instance principals or User principals ? Can you provide more details about the error (logs, screenshot). Thanks.

**Comment by mamorett** [comment]
We released yesterday v5 of the plugin which should fix this issue.
