### ISSUE TITLE
Namespace pulldown empty when Policy with "where target.metrics.namespace=<namespace>" clause used

### ISSUE THREAD

**Issue by aucado** [oracle/oci-grafana-metrics#217]
I got the query builder working and the pulldown populates with my namespaces in the available compartment. However when I added the where clause to my policy statement it blocks all of the namespaces including the one allowed by the where clause.

**Comment by mamorett** [comment]
Hi. Can you share the policy statement you applied ?

**Comment by aucado** [comment]
With some further testing it seems that the policy statement
'allow group <group> to read metrics in compartment <compartment> where target.metrics.namespace='<namespace>'
used the namespace value can only be oci supported metrics and was only not working for my custom metric namespace name and behaved the same when using the metrics explorer in oci monitorign.
