### ISSUE TITLE
change labels of selected items

### ISSUE THREAD

**Issue by damikem** [oracle/oci-grafana-metrics#22]
instead of seeing:
CpuUtilization, {node-1.phx1.mycompartment.com}
CpuUtilization, {node-2.phx1.mycompartment.com}
CpuUtilization, {node-3.phx1.mycompartment.com}
At the panel's table, I'd like to have a way to edit the display names for example to:
node-1.phx1
node-2.phx1
node-3.phx1
This will make the dashboard cleaner and more user friendly.

**Comment by jsalaman** [comment]
Yes please we need this enhancement for cleaner labeling on dashboards

**Comment by huskerdhf** [comment]
Hi @damikem,

This issue has been addressed as part of https://github.com/oracle/oci-grafana-metrics/pull/131 including updates to the plugin documentation. The changes for this PR will be included in the next official version of the plugin which should be coming out within the next few weeks. In the mean time you can download and build the plugin on your own to try out this enhancement.

Thanks
