### ISSUE TITLE
Data Source is not working while integrating Grafana with OCI

### ISSUE THREAD

**Issue by vijayasri-a** [oracle/oci-grafana-metrics#227]
![Datasource](https://github.com/oracle/oci-grafana-metrics/assets/126856592/25b693b7-47fe-48c0-a343-693ddaf8a90c)

**Comment by shaliniebizoncloud** [comment]
I also fasing this same issue in my grafana please suggest how to resolve this error.

**Comment by mamorett** [comment]
Data source not working means that you may have some misconfiguration in your parameters or that your user account does not have the policies correctly set up. Can you check your Grafana logs while testing the datasource and see if there are some error messages ?

**Comment by mamorett** [comment]
Plugin version 5.0.0 is released. Please try to upgrade to this version and double check your connection parameters if that fix the issue.
