### ISSUE TITLE
can´t connect with datasource to eu-madrid-2 (EU Sovereign South Madrid)

### ISSUE THREAD

**Issue by juan-martinez-herrero** [oracle/oci-grafana-metrics#254]
What happened?
We try to connect from grafana cloud to OCI eu-madrid-2 with "oracle cloud infrastructure metrics" plugin.
We installed it, but when we try to connect datasource to eu-madrid-2 it don´t appear to select. 
Only eu-madrid-1. We have a sovereign cloud.

What was expected to happen?
We want to connect grafana cloud to eu-madrid-2 (EU Sovereign South Madrid)

Steps to reproduce the problem:

1. Install Oracle Cloud Infrastructure Metrics pluggin in grafana cloud.
2. Add a datasource from pluggin, and configure OCI parameters.
3. We can´t select eu-madrid-2 (only eu-madrid-1)
4. If we click save&test with our correct parameters, appears the error: "TestConnectivity failed: cannot read Compartments in profile DEFAULT/" because we only can check eu-madrid-1, instead eu-madrid-2 (the EU Sovereign South Madrid)

**Comment by mamorett** [comment]
V 5.04 of the plugin now supports Sovereign regions.

**Comment by mamorett** [comment]
Hi. Please update to the latest version of the plugin (v5.1.0). It should work with all Sovereign cloud tenancies.
