### ISSUE TITLE
Grafana 500 error installing oci-datasource plugin

### ISSUE THREAD

**Issue by mvandervliet** [oracle/oci-grafana-metrics#26]
When installing the `oci-datasource` plugin, an api call is made to load the plugin metadata:
https://grafana.com/api/plugins/oci-datasource

The response includes an invalid `url` for the repository, which results in an error when attempting to fetch release/1.0.2

https://grafana.com/api/plugins/oci-datasource/versions/1.0.2/download

**Comment by dvdwende** [comment]
+ 1 for issue

{
  "code": "Internal",
  "message": "Couldn't load https://api.github.com/repos/grafana/oci-datasource/zipball/575707096aecfd6ad416630b0654d73fcd1f4d0b: 404 {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/repos/contents/#get-archive-link\"}"
}

**Comment by suri1240** [comment]
I'm also getting the same issue, can anyone have any idea on it.

**Comment by MGralike** [comment]
What worked for me were the steps (in my case Linux) described in the github doc readme's. In other words, I did not use the "grafana method" but used "wget":

Download the OCI Grafana Plugin: 

wget https://github.com/oracle/oci-grafana-plugin/releases/download/V1.0.4/plugin.tar. 

Create a directory and install the plugin: mkdir oci && tar -C oci -xvf plugin.tar and then remove the tarball: rm plugin.tar.

**Comment by dvdwende** [comment]
Thanks for the info.
