### ISSUE TITLE
Feature request - Native Grafana Datasource Alerting support 

### ISSUE THREAD

**Issue by MGralike** [oracle/oci-grafana-metrics#27]
If possible, I would really like to have support for Native datasource alerting for the OCI datasource. 

![Schermafbeelding 2019-11-18 om 13 17 42](https://user-images.githubusercontent.com/8393411/69051954-08af2900-0a06-11ea-9f6c-ef46aea3e74e.png)

**Comment by subsahu123** [comment]
We are looking for this feature as well

**Comment by MaikiGirardi** [comment]
We too...

**Comment by simmalra** [comment]
Same here. Need it badly.

**Comment by nutslove** [comment]
Same here. Need it badly!!

**Comment by mfraigneau** [comment]
Same here. Need it badly!!!!!!!!!!

**Comment by mamorett** [comment]
Alert is now available in the Version 5.5 of the plugin on Grafana catalogue too.
