### ISSUE TITLE
Alerting feature release

### ISSUE THREAD

**Issue by ybalasubramaniam** [oracle/oci-grafana-metrics#270]
Hello,

We are looking to implement alerting feature of Oracle Cloud Infrastructure Metrics datasource. Could you kindly let us know when the release would be available for this? 

We see that https://github.com/oracle/oci-grafana-metrics/pull/268 is already merged.

Thanks

**Comment by mamorett** [comment]
Alert is now available in the Version 5.5 of the plugin on Grafana catalogue too.
