### ISSUE TITLE
Access to other metrics such as Cost Analysis

### ISSUE THREAD

**Issue by brasrox** [oracle/oci-grafana-metrics#276]
It would be great to be able to use this plugin to get other metrics, such as their rest API to get the daily cost of the cloud infrastructure

https://docs.oracle.com/en-us/iaas/api/#/en/usage/20200107/

It is possible?

**Comment by mamorett** [comment]
Hi @brasrox . These reports (https://docs.oracle.com/en-us/iaas/Content/Billing/Concepts/usagereportsoverview.htm) are not in metric format, but are cvs saved daily in object storage. Also the API is from different families, usageapi for these reports, while metrics is using telemetry family. So I would say, no, it is not possible to access the Cost Analysis reports from OCI Grafana Metrics plugin.
