### ISSUE TITLE
Oracle Sovereign Cloud Region ap-hobsonville-1 to be added

### ISSUE THREAD

**Issue by buddikaMSD** [oracle/oci-grafana-metrics#299]
Hello There,
We are trialling out on-premises Grafana with the OCI plugin to connect to a sovereign cloud region ap-hobsonville-1 that is deployed in NZ. At the moment this region is not available for selection and was wondering whether this region will be added to the plugin? If not is there a way to configure this region to be used with the OCI Grafana Plugin. I am using the latest version 6.0.0.

Thanks,
Buddika

**Comment by mamorett** [comment]
Hi. I can see the region included already in the regionlist: https://github.com/oracle/oci-grafana-metrics/blob/master/src/config.options.ts. Can yoy try to upgrade to 6.0.1 ?

**Comment by mamorett** [comment]
Just tried, and I confirm the region is there: 
![image](https://github.com/user-attachments/assets/7bcfada1-a580-46c5-bbeb-210219e393d7)

**Comment by buddikaMSD** [comment]
IN-CONFIDENCE

Hi,

Thank you for your response. I have refreshed the plugin to 6.0.1 and now I see the region. Really appreciate your response.

Thanks,

Buddika

**Comment by buddikaMSD** [comment]
Thank you. I have refreshed the plugin to 6.0.1 and now I can see the region. Thanks.

**Comment by buddikaMSD** [comment]
Closing the issue as it has been successfully resolved.
