### ISSUE TITLE
Get this datasource into grafana cloud?

### ISSUE THREAD

**Issue by srclosson** [oracle/oci-grafana-metrics#303]
Hi there, I'm a solutions engineer for Grafana, and I'd love to see this datasource get signed and into grafana cloud.

Thoughts?

**Comment by mamorett** [comment]
Hi @srclosson . Yes the plugin works in Grafana Cloud too. You can install it using the Grafana catalogue, like any other plugin. However the datasource, in Grafana Cloud, can be configured in User principal only. You can refer to this document for further info: https://github.com/oracle/oci-grafana-metrics/blob/master/docs/grafanacloud.md
