### ISSUE TITLE
Grafana reports error when we exports json file of dashboards from one instance to the other.

### ISSUE THREAD

**Issue by zhfkt** [oracle/oci-grafana-metrics#34]
Hi Team,

We are using Grafana and Oci-grafana-plugin on the 2 instances. We manually configure the dashboards of Grafana on one instance, and would like to export json file and import it to another instance.  Here are the steps:

1. Export dashboards to the json file on the one instance

![image](https://user-images.githubusercontent.com/4969804/72497847-a5f0d700-3868-11ea-8e3f-ecb5170c3756.png)

2. Import dashboards from the json file on another instance

![image](https://user-images.githubusercontent.com/4969804/72497928-d769a280-3868-11ea-830b-a699858a7ca3.png)

However, after exporting completed, the new dashboards reported error.

![image](https://user-images.githubusercontent.com/4969804/72497997-041dba00-3869-11ea-9e0b-99b75ee6fae8.png)

"
Unable to get namespaces: Error: reject: too many failed attempts: {"data":{"message":"Metric request error"},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/tsdb/query","data":{"from":"1579133064299","to":"1579154664299","queries":[{"environment":"local","datasourceId":1,"tenancyOCID":"ocid1.tenancy.oc1..aaaaaaaa7i5g7zgn62tb4f7x4gtuafleeykbv45tgldnmga7esctdmjtfqqq","queryType":"namespaces","region":"undefined","compartment":"ocid1.tenancy.oc1..aaaaaaaa7i5g7zgn62tb4f7x4gtuafleeykbv45tgldnmga7esctdmjtfqqq"}]},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Internal Server Error","xhrStatus":"complete"}
"
After I select to the correct filter, the chart can show on the new dashboard.

![image](https://user-images.githubusercontent.com/4969804/72498100-52cb5400-3869-11ea-8c56-d479c85ba1bb.png)

But when I enter into the dashboard next time, it will still report error if I didn't select the filter on purpose.

Pls suggest whether there is any to avoid error on this issue.

Thank you !

**Comment by mamorett** [comment]
I am not able to reproduce this issue with v3, v4 and v5 of the plugin. I think this is working as expected, maybe was related to some old version.
