### ISSUE TITLE
The dimension values in Grafana feteched by oci-grafana-plugin are missing.

### ISSUE THREAD

**Issue by zhfkt** [oracle/oci-grafana-metrics#35]
Hi Team,

We are using Grafana and Oci-grafana-plugin on our instance. We are checking the dimension values in our one Grafana  variable, and found that there are some values missing.

1. Here is the screenshot from Telemetry
![image](https://user-images.githubusercontent.com/4969804/72498861-45af6480-386b-11ea-864c-1e491e523d9b.png)
2. Here is the screenshot from Grafana.
![image](https://user-images.githubusercontent.com/4969804/72499098-e736b600-386b-11ea-8218-355ad25cc4ad.png)
3. Here is the variable defined in the Grafana dashboard
![image](https://user-images.githubusercontent.com/4969804/72499163-05041b00-386c-11ea-9c29-c888addd42c3.png)

We could see that there are only 2 values in the dimension value in the Grafana screenshot . But on the Telemetry screenshot, it contains the values larger than 2.

Pls review the issue.

Thank you !

**Comment by mamorett** [comment]
dimensions query and retrieval function changed from v5.x of plugin, and I cannot see this behaviour since then.
