### ISSUE TITLE
Need the support for "alias" in the chart defination.

### ISSUE THREAD

**Issue by zhfkt** [oracle/oci-grafana-metrics#36]
Hi ,

I could see there is the "alias" field for the original Grafana .

![image](https://user-images.githubusercontent.com/4969804/72697557-4271ec80-3b7b-11ea-8dd2-2be10e6f5454.png)

However, in the current oci-grafana-plugin , I am not able to find the "Alias".  So that the name in the chart and table can not be changed and aliased.  

![image](https://user-images.githubusercontent.com/4969804/72697833-608c1c80-3b7c-11ea-8d38-45e55011995a.png)
![image](https://user-images.githubusercontent.com/4969804/72697841-71d52900-3b7c-11ea-89ac-24253829d43a.png)

Pls review

**Comment by huskerdhf** [comment]
Hi @zhfkt,

This issue has been addressed as part of [PR #131](https://github.com/oracle/oci-grafana-metrics/pull/131) including updates to the plugin documentation. The changes for this PR will be included in the next official version of the plugin which should be coming out within the next few weeks. In the mean time you can download and build the plugin on your own to try out this enhancement.

Thanks

**Comment by zhfkt** [comment]
> Hi @zhfkt,
> 
> This issue has been addressed as part of [PR #131](https://github.com/oracle/oci-grafana-metrics/pull/131) including updates to the plugin documentation. The changes for this PR will be included in the next official version of the plugin which should be coming out within the next few weeks. In the mean time you can download and build the plugin on your own to try out this enhancement.
> 
> Thanks

Thanks.
