### ISSUE TITLE
Data source is not working - Docker configuration

### ISSUE THREAD

**Issue by mattiaoui** [oracle/oci-grafana-metrics#43]
hello,
i'm running garfana on my docker server,and i have install the OCI plug-in and it's work.
After OCI configuration on garfana i receve the error "Data source is not working", but i don't have idea to install oci cli on my garfana container.

Thanks
Mattia

**Comment by mamorett** [comment]
OCI CLI is no longer required since V4 of the plugin. I would recommend to upgrade your plugin version.
