### ISSUE TITLE
Plugin Deprecated on Grafana

### ISSUE THREAD

**Issue by jeevanjoseph** [oracle/oci-grafana-metrics#50]
Why does grafana.com list this plugin as "deprecated". I see activity on the github repo, but the last release on grafana.com seems to have been over a year ago ?

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5790082/83090073-af772080-a04c-11ea-8ba3-2eabdad3443b.png">

**Comment by jeevanjoseph** [comment]
Any update ?

**Comment by onlyvmal** [comment]
Jeevan, we are still supporting this plugin from this GitHub location.

**Comment by jeevanjoseph** [comment]
@onlyvmal - any reason why its just the  github repo and not on grafana.com ?
I typically use the grafana helm chart to install grafana - manual installation of plugins is a chore - the helm charts would just let me specify what plugins (from grafana.com) I want installed on any grafana deployment I spin up

**Comment by jeevanjoseph** [comment]
bump.
Is this related to the  new plugin architecture in grafana 7.0 ?

**Comment by MaikiGirardi** [comment]
Is there any update about this issue? It's relevant use the official grafana repo.

**Comment by kz4d1x** [comment]
The plugin is supported and officially released on Grafana.com, see the latest release here: https://grafana.com/grafana/plugins/oci-metrics-datasource/
