### ISSUE TITLE
Grafana Plugin oci-grafana-plugin did not support GOV tenancy

### ISSUE THREAD

**Issue by zhfkt** [oracle/oci-grafana-metrics#58]
We are setting up oci-grafana-plugin for the Grafana on the UK Gov 

The region name of UK Gov tenancy is uk-gov-london-1. However, when I created the datasource by oci-grafana-plugin. I am not able to find the the uk-gov-london-1 in the region dropmenu and there is only ashburn, phoenix and so on. The UK Gov tenancy didn't contain the ashburn, phoenix or the other region mentioned in the menu list.  The UK Gov tenancy only contains the region uk-gov-london-1.

![image](https://user-images.githubusercontent.com/4969804/88474864-48e38580-cf5d-11ea-92cc-2939c2182c06.png)

 

When I created the datasource on the Grafana by oci-grafana-plugin, if I selected the region not existed in the tenancy, it will reported the error. So when I created the datasource for UK Gov tenancy, it will report error because the menu list didn't contian any region for the UK Gov tenancy .

 

This request is to support Grafana Plugin oci-grafana-plugin on the GOV tenancy. Thank you !

**Comment by mayurOciSA** [comment]
closing since gov regions are supported in recent version of the plugin
