### ISSUE TITLE
Grafana query for subcompartment based on the region and parent compartment selected

### ISSUE THREAD

**Issue by varmaimmalraju** [oracle/oci-grafana-metrics#59]
With the current grafana dashboard variables available we can only query the top level compartments. If the instances are under a subcompartment the metrics pull is not working. Is there any query available to query the subcompartments based on the parent compartment selected and eventual be able to show metrics for oci resources.

So looking for something like
region - parent compartment - Subcompartment - Namespace

Really appreciate if any help can be provided.

Thanks.

**Comment by routp** [comment]
This is a valid requirement. We have subcompartments and the selection only pulls top-level compartments or subcompartments of only one parent. For example, if there are two-parent compartments having child compartments with the same name (e.g. CHC1, CHC2), the datasource only shows one set that too without any reference to their parent. 
PC1
    - CHC1
    - CHC2
PC2
   - CHC1
   - CHC2

As a workaround, we are adding missing compartments OCID to the query to make it work but this becomes tedious. The drop-down should show in the format like PC1/CHC1 and PC1/CHC2 or a collapsible way how OCI console shows to pick the desired compartment.

**Comment by simmalra** [comment]
Thanks @routp for the tip. Tedious but helps. I have around 20-30 environments :-(. Hope the plugin gets enhanced.

**Comment by duhang** [comment]
A lot of our sub-compartment have the exactly same names.

This plugin need differentiate them by "compartment/sub-compartment"
Or should just take an existing "compartment" variable with pre-populated ocid for (sub-)compartment

**Comment by mayurOciSA** [comment]
closing since the plugin now supports fully qualified names
